<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nhn Vt_jet-tabs__label-image (5)</name>
   <tag></tag>
   <elementGuidId>ef5b4f7e-fae0-4b70-bf88-98f097f59ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jet-tabs-control-5699']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jet-tabs-control-5699 > div.jet-tabs__control-inner > img.jet-tabs__label-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jet-tabs-control-5699 img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4712bf0b-7cec-4ca3-ba36-1e1d45c335f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jet-tabs__label-image</value>
      <webElementGuid>831ba91c-1f6e-47b0-b8d2-b5bff09e1e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-bang.webp</value>
      <webElementGuid>43aa8b94-64f6-42a5-962c-ebf8b6d2e1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jet-tabs-control-5699&quot;)/div[@class=&quot;jet-tabs__control-inner&quot;]/img[@class=&quot;jet-tabs__label-image&quot;]</value>
      <webElementGuid>509d5f1d-5adb-4b8a-834a-161f47bb38ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jet-tabs-control-5699']/div/img</value>
      <webElementGuid>1af04eda-11bf-45c0-a6b4-17f4e83721d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-bang.webp')]</value>
      <webElementGuid>7afebf61-32a7-4610-9f04-aa676ab8041c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/img</value>
      <webElementGuid>ebb7a618-d6c5-46ed-92b4-f9c9cf2340e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-bang.webp']</value>
      <webElementGuid>cd91ca48-837e-40bb-9f27-f2afe2383485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
