<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_012butterfree</name>
   <tag></tag>
   <elementGuidId>64bf625c-6710-4ed0-a97b-ce90775e3932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/ul/li[12]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(12) > div.thumbnail__container.noselect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;#012butterfree&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f13fca2-2a3f-4603-87cf-983768174630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumbnail__container noselect</value>
      <webElementGuid>0aeb38da-91de-44c8-a1c7-00902ad13509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#012butterfree</value>
      <webElementGuid>6cec0b6b-ddf5-4e1b-89a5-069a1dd835eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container&quot;]/div[@class=&quot;pokemon__container&quot;]/div[@class=&quot;all__pokemons&quot;]/ul[1]/li[12]/div[@class=&quot;thumbnail__container noselect&quot;]</value>
      <webElementGuid>4e7ab14a-558e-416b-90e7-a1c4c335342b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/ul/li[12]/div</value>
      <webElementGuid>d926fc5f-804a-4805-bc12-073837ccc52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='metapod'])[1]/following::div[3]</value>
      <webElementGuid>2e189144-5387-4843-ae7a-ba68869ece42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#011'])[1]/following::div[6]</value>
      <webElementGuid>d01a25b2-8f83-4989-bcb3-02e04205153b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div</value>
      <webElementGuid>5ef23678-1253-4813-b282-1c3e076846df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '#012butterfree' or . = '#012butterfree')]</value>
      <webElementGuid>fa37ca9a-3408-40a0-a864-a006b7ba7dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
