<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_051dugtrio</name>
   <tag></tag>
   <elementGuidId>aa9d5837-4063-457c-b31d-af885281f601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/ul/li[51]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(51) > div.thumbnail__container.noselect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;#051dugtrio&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd474b6a-51c7-41c3-8f8a-8a879a7fb112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumbnail__container noselect</value>
      <webElementGuid>ad4086d6-f95a-433d-b983-5e20fc9898ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#051dugtrio</value>
      <webElementGuid>b01b98bf-0f08-48a8-9b41-c4f2e9794d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container&quot;]/div[@class=&quot;pokemon__container&quot;]/div[@class=&quot;all__pokemons&quot;]/ul[1]/li[51]/div[@class=&quot;thumbnail__container noselect&quot;]</value>
      <webElementGuid>0087c7cd-544f-463a-91ac-5640eb651466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/ul/li[51]/div</value>
      <webElementGuid>d9bd99a0-9619-41cd-8b14-528fcaa9c4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='diglett'])[1]/following::div[3]</value>
      <webElementGuid>a1d492b6-3054-4bb0-b570-a3b71f07ae23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#050'])[1]/following::div[6]</value>
      <webElementGuid>d2b5a25f-da4a-4082-8679-36d3217a46d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[51]/div</value>
      <webElementGuid>c1c58727-f28d-49d5-97fc-9f780dcc7be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '#051dugtrio' or . = '#051dugtrio')]</value>
      <webElementGuid>fb32c404-4a81-4a3f-b22a-4b8633b9910a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
