<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_bulbasaurivysaurvenusaur</name>
   <tag></tag>
   <elementGuidId>06a758bf-7bbf-4c89-b707-0ba8593d81f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Evolution'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.evolution__box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;bulbasaurivysaurvenusaur&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ca81378-466f-4a54-9a89-0abc866045df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>evolution__box</value>
      <webElementGuid>b7e41772-2bc5-49e5-b3fe-5f327a38887c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bulbasaurivysaurvenusaur</value>
      <webElementGuid>30a00daa-7398-43c6-953f-f8bc94caab6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root dialog__bg noselect&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper&quot;]/div[@class=&quot;MuiPaper-root MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthMd MuiDialog-paperFullWidth MuiPaper-elevation24 MuiPaper-rounded&quot;]/div[@class=&quot;MuiDialogContent-root jss4 dialog__content&quot;]/div[@class=&quot;info__container&quot;]/div[@class=&quot;info__container__data&quot;]/div[@class=&quot;right__box&quot;]/div[4]/div[@class=&quot;evolution__box&quot;]</value>
      <webElementGuid>a1f996ec-74e9-4f6d-82d1-fcb04c31ab28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evolution'])[1]/following::div[1]</value>
      <webElementGuid>c0225c51-d11a-428b-a099-7a0412d9a228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='speed'])[1]/following::div[4]</value>
      <webElementGuid>c65673f3-f037-47b3-bcf2-0aeb1c63c16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>2b9ee30a-c161-415c-bc09-b95ebae37aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'bulbasaurivysaurvenusaur' or . = 'bulbasaurivysaurvenusaur')]</value>
      <webElementGuid>23c120f0-7115-462d-9be4-e035394dac58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
