<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Xo Hiu ng Xu_jet-tabs__label-image (1)</name>
   <tag></tag>
   <elementGuidId>9700ae0f-41c7-4c1d-8d48-1fed4aaa1100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jet-tabs-control-4904']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jet-tabs-control-4904 > div.jet-tabs__control-inner > img.jet-tabs__label-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jet-tabs-control-4904 img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>41a2ab75-4d02-4e84-8979-0f3ccb77aa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jet-tabs__label-image</value>
      <webElementGuid>f55a892a-de08-4b16-a5f3-a9a759284511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://honkai-builds.com/wp-content/uploads/2023/04/5-sao.png</value>
      <webElementGuid>fb781efd-e4b4-4aa8-a2ad-7f45593910b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jet-tabs-control-4904&quot;)/div[@class=&quot;jet-tabs__control-inner&quot;]/img[@class=&quot;jet-tabs__label-image&quot;]</value>
      <webElementGuid>83e01c8e-a678-488a-9243-16ef5ff6fda6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jet-tabs-control-4904']/div/img</value>
      <webElementGuid>22d888a4-21e2-4253-b992-cbb241d61734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://honkai-builds.com/wp-content/uploads/2023/04/5-sao.png')]</value>
      <webElementGuid>71f3c5e2-efa6-4504-8976-9beb91b4d344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>56b95b2a-91be-43bd-9682-1a857436bf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://honkai-builds.com/wp-content/uploads/2023/04/5-sao.png']</value>
      <webElementGuid>e7ef585b-dbc2-415e-b473-00491af520a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
