<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DPS nh n</name>
   <tag></tag>
   <elementGuidId>37b4318d-218c-481a-82af-f1d9ee4f5d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jet-tabs-control-1422']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jet-tabs-control-1422 > div.jet-tabs__control-inner > div.jet-tabs__label-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;DPS Đánh Đơn&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c969a618-34c6-4112-b523-60340420416a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jet-tabs__label-text</value>
      <webElementGuid>4c617485-51d9-47c9-85e3-c19f8f2dfd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DPS Đánh Đơn</value>
      <webElementGuid>354cccb4-b6f9-4140-ba4b-906792d63dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jet-tabs-control-1422&quot;)/div[@class=&quot;jet-tabs__control-inner&quot;]/div[@class=&quot;jet-tabs__label-text&quot;]</value>
      <webElementGuid>a09d97ca-1d36-4498-b200-7b6f40b6c4df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jet-tabs-control-1422']/div/div</value>
      <webElementGuid>333c8b85-05b1-4416-aad1-5d90a630e193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng Thể'])[1]/following::div[3]</value>
      <webElementGuid>6ea9893c-9ec2-46ae-9f58-575dd56f2854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xếp Hạng'])[5]/following::div[13]</value>
      <webElementGuid>4f421984-e538-4efa-b770-9dd4ae04240d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DPS Đánh Lan'])[1]/preceding::div[1]</value>
      <webElementGuid>2f9a1baf-2e78-4c59-87e8-e2abd63d0f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hỗ Trợ'])[1]/preceding::div[4]</value>
      <webElementGuid>f4310f52-ba5b-480c-88a6-ff606640a0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DPS Đánh Đơn']/parent::*</value>
      <webElementGuid>1c04e2a6-3d63-466e-abcd-086a768196de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>b9d7130d-cf3e-4161-8e2a-ae8f2e63d329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DPS Đánh Đơn' or . = 'DPS Đánh Đơn')]</value>
      <webElementGuid>778412fb-9953-4215-b30d-34fdaff0f26d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
