<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Recommended for You2024 Chevrolet Silve_87628b</name>
   <tag></tag>
   <elementGuidId>5ebdd8d2-0fac-4edf-89d4-2465f9c9bb7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stepModuleContainer']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-13rh4em.etn5x2f11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Recommended for You2024 Chevrolet Silverado 1500 Double Cab$40,745Starting Price&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba863846-d5ba-4c4a-bb6b-8c827fb0f09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>90cf0c87-82a4-45d4-a520-50ea4a9ef943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctaurl</name>
      <type>Main</type>
      <value>https://www.kbb.com/chevrolet/silverado-1500-double-cab/2024/</value>
      <webElementGuid>264e8024-1edf-4d59-83fc-4befa96aec14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lean-auto</name>
      <type>Main</type>
      <value>hp-shop-guide-2</value>
      <webElementGuid>b851cd42-0ebb-4abf-88c6-406562a6b9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>Shoppers_LastCarSearched</value>
      <webElementGuid>477bac76-04c2-48a4-8d17-569cb1840d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-type</name>
      <type>Main</type>
      <value>click,impression</value>
      <webElementGuid>fafa89f3-c66b-45b3-8519-d9f7fc796019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-13rh4em etn5x2f11</value>
      <webElementGuid>323bc20d-bc29-4cd5-9d74-2bc7e343c17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recommended for You2024 Chevrolet Silverado 1500 Double Cab$40,745Starting PriceSee pricing &amp; moreShop this Car</value>
      <webElementGuid>f6665bcf-a9cb-4b53-8d94-950f80159d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepModuleContainer&quot;)/div[@class=&quot;css-td2030 e6p01070&quot;]/div[@class=&quot;css-13rh4em etn5x2f11&quot;]</value>
      <webElementGuid>bdb97ca1-720b-4612-adf9-a6c6ed925905</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stepModuleContainer']/div/div[2]</value>
      <webElementGuid>9767dbb4-7247-482e-9859-4bae2edf4a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start with Your Current Car'])[1]/following::div[2]</value>
      <webElementGuid>aeb85ede-49ed-4af4-8616-2d56bd5d5918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>8140c479-1f1b-4930-b0a2-72327ba8bad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Recommended for You2024 Chevrolet Silverado 1500 Double Cab$40,745Starting PriceSee pricing &amp; moreShop this Car' or . = 'Recommended for You2024 Chevrolet Silverado 1500 Double Cab$40,745Starting PriceSee pricing &amp; moreShop this Car')]</value>
      <webElementGuid>15b3e63a-a76f-48fd-a5b1-d09a5c295502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
