<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Accessible Menu - Main MenuCar Value_119c48</name>
   <tag></tag>
   <elementGuidId>e3aabc03-1031-4eb8-95b6-92054fa31023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header.css-kzuwlq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>3c3ed402-cff1-4fe6-80b8-7394ebd772e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kzuwlq</value>
      <webElementGuid>b491b040-fad0-45a2-915f-edb82581727c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accessible Menu - Main MenuCar ValuesPrice New/UsedMy Car's ValueInstant Cash OfferCars for SaleCars for SaleFree Dealer Price QuoteVehicle History ReportFind Local DealersPrivate Seller ExchangePrivate Seller CarsSell Your CarCar ReviewsBest CarsDealer ReviewsKBB Expert ReviewsElectric Vehicle GuideKBB AwardsLatest Car NewsCar RepairAuto Repair PricesCar RecallsMaintenance PricingFind an Auto ShopService AdvisorOBD-II CodesResearch ToolsCar ResearchCar FinderCompare CarsVehicle History ReportCar ValuesCar LoansInsuranceCheck My CreditExtended WarrantyRecalls</value>
      <webElementGuid>6faad9ff-44b9-4552-a35d-437b65d2176f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[@class=&quot;css-kzuwlq&quot;]</value>
      <webElementGuid>54381d30-5978-4309-ace0-099cbbf3d4a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header</value>
      <webElementGuid>cdf99d6d-a3af-448f-b5ef-c8603bd5b0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::header[1]</value>
      <webElementGuid>e6a02a63-6eed-4d28-8c1a-0ebaecf95006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>4f27c3a6-477b-4467-8328-18952ecee7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = concat(&quot;Accessible Menu - Main MenuCar ValuesPrice New/UsedMy Car&quot; , &quot;'&quot; , &quot;s ValueInstant Cash OfferCars for SaleCars for SaleFree Dealer Price QuoteVehicle History ReportFind Local DealersPrivate Seller ExchangePrivate Seller CarsSell Your CarCar ReviewsBest CarsDealer ReviewsKBB Expert ReviewsElectric Vehicle GuideKBB AwardsLatest Car NewsCar RepairAuto Repair PricesCar RecallsMaintenance PricingFind an Auto ShopService AdvisorOBD-II CodesResearch ToolsCar ResearchCar FinderCompare CarsVehicle History ReportCar ValuesCar LoansInsuranceCheck My CreditExtended WarrantyRecalls&quot;) or . = concat(&quot;Accessible Menu - Main MenuCar ValuesPrice New/UsedMy Car&quot; , &quot;'&quot; , &quot;s ValueInstant Cash OfferCars for SaleCars for SaleFree Dealer Price QuoteVehicle History ReportFind Local DealersPrivate Seller ExchangePrivate Seller CarsSell Your CarCar ReviewsBest CarsDealer ReviewsKBB Expert ReviewsElectric Vehicle GuideKBB AwardsLatest Car NewsCar RepairAuto Repair PricesCar RecallsMaintenance PricingFind an Auto ShopService AdvisorOBD-II CodesResearch ToolsCar ResearchCar FinderCompare CarsVehicle History ReportCar ValuesCar LoansInsuranceCheck My CreditExtended WarrantyRecalls&quot;))]</value>
      <webElementGuid>a6d10561-dbef-4f03-b5a4-258e5f83df7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
