<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_H Tr</name>
   <tag></tag>
   <elementGuidId>a516a7d4-c50a-4478-9b91-2bddb9c260de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jet-tabs-control-1424']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jet-tabs-control-1424 > div.jet-tabs__control-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Hỗ Trợ&quot;i] >> div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8aed814-30b5-4112-b576-d6fb7e9bbbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jet-tabs__control-inner</value>
      <webElementGuid>998c4a4f-7405-4f2b-b00f-6f0dc550e2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hỗ Trợ</value>
      <webElementGuid>92d05bfd-c982-4f57-9c25-55c5c3f2821b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jet-tabs-control-1424&quot;)/div[@class=&quot;jet-tabs__control-inner&quot;]</value>
      <webElementGuid>9f276f67-ca24-4e2b-9961-2fe829a93681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jet-tabs-control-1424']/div</value>
      <webElementGuid>2da69ac1-6170-4a53-8354-3692b6698f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DPS Đánh Lan'])[1]/following::div[2]</value>
      <webElementGuid>bed6f6bb-4362-443a-b414-a82b6122cd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DPS Đánh Đơn'])[1]/following::div[5]</value>
      <webElementGuid>05c71188-88ba-4bc3-a9fa-8e6bec4ea91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SS'])[1]/preceding::div[2]</value>
      <webElementGuid>749f226c-5d51-430a-a94e-ded27635d730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>ecce0c4d-1958-44ac-922d-f55f6064b155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hỗ Trợ' or . = 'Hỗ Trợ')]</value>
      <webElementGuid>db029c95-78dd-45f4-a773-56e076db09cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
