<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nhn Vt_jet-tabs__label-image (4)</name>
   <tag></tag>
   <elementGuidId>19ee2b52-8377-49a5-94c3-ac0a07107b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jet-tabs-control-5697']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jet-tabs-control-5697 > div.jet-tabs__control-inner > img.jet-tabs__label-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jet-tabs-control-5697 img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4b61f74c-7666-427f-bce6-774113dca7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jet-tabs__label-image</value>
      <webElementGuid>88ca9d68-0bed-4f99-802f-cec49ffea018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-loi.webp</value>
      <webElementGuid>736bcc67-96e6-4717-b78d-249258cb2768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jet-tabs-control-5697&quot;)/div[@class=&quot;jet-tabs__control-inner&quot;]/img[@class=&quot;jet-tabs__label-image&quot;]</value>
      <webElementGuid>59ba4c9f-9d24-4619-ac27-e63fc65d87de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jet-tabs-control-5697']/div/img</value>
      <webElementGuid>56a0507b-a1cb-447a-b439-4c3ef76b215a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-loi.webp')]</value>
      <webElementGuid>d6db58e3-87d1-4646-ab8d-242e5b543661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/img</value>
      <webElementGuid>5dd6ff85-bb17-4655-b981-5db64339e18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-loi.webp']</value>
      <webElementGuid>a63826e4-dfde-41eb-a4ce-76afc6ca920e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
