<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nhn Vt_jet-tabs__label-image (2)</name>
   <tag></tag>
   <elementGuidId>f3a70c77-ae8e-4f39-a2b0-e5d5a2cd01a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jet-tabs-control-5695']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jet-tabs-control-5695 > div.jet-tabs__control-inner > img.jet-tabs__label-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jet-tabs-control-5695 img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3600a2b6-f215-4dda-8238-d8c417cd595e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jet-tabs__label-image</value>
      <webElementGuid>c6501122-b408-4dea-a309-308fae107351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-phong.webp</value>
      <webElementGuid>abf9f56e-28a0-4d49-8d55-680006137f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jet-tabs-control-5695&quot;)/div[@class=&quot;jet-tabs__control-inner&quot;]/img[@class=&quot;jet-tabs__label-image&quot;]</value>
      <webElementGuid>1cb2dc5f-2b13-4252-840c-ff610dfe2446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jet-tabs-control-5695']/div/img</value>
      <webElementGuid>c81d9a26-9250-4355-b93b-8154524c2df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-phong.webp')]</value>
      <webElementGuid>b86eeb1c-0562-4a61-b763-683c9a593520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/img</value>
      <webElementGuid>2121381c-edf4-4f01-b849-2e417b3889fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-phong.webp']</value>
      <webElementGuid>8e47b3f9-f5ab-468d-a835-6225846be9fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
