<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nhn Vt_jet-tabs__label-image (3)</name>
   <tag></tag>
   <elementGuidId>f683bd14-3657-4e1a-91f8-0981f84246ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jet-tabs-control-5696']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jet-tabs-control-5696 > div.jet-tabs__control-inner > img.jet-tabs__label-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jet-tabs-control-5696 img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22a43cb5-7cab-48de-8a46-4c507a624227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jet-tabs__label-image</value>
      <webElementGuid>c638a15b-93ca-46a2-8272-cd19130ac4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-luong-tu.webp</value>
      <webElementGuid>059e080a-a35f-4fae-8951-0cd7f65dac7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jet-tabs-control-5696&quot;)/div[@class=&quot;jet-tabs__control-inner&quot;]/img[@class=&quot;jet-tabs__label-image&quot;]</value>
      <webElementGuid>f493385a-0b82-4514-b37f-b5e535c1c646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jet-tabs-control-5696']/div/img</value>
      <webElementGuid>e63215b8-1f2f-408f-985b-27ca2cf7ab77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-luong-tu.webp')]</value>
      <webElementGuid>049b6f11-1a9e-4cf8-bfdd-c7d735ff2749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/img</value>
      <webElementGuid>0020e1f7-f3f4-4f2e-9584-5e7f4955d18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://honkai-builds.com/wp-content/uploads/2023/04/nguyen-to-luong-tu.webp']</value>
      <webElementGuid>d9ff8e49-d452-49e2-bd12-27debe7be17a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
