<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Know Your ScoreCar shopping Check your _71532d</name>
   <tag></tag>
   <elementGuidId>a1caff89-19eb-4d4c-8b2a-c12eaf642b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stepModuleContainer']/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-13rh4em.etn5x2f11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Know Your ScoreCar shopping? Check your credit health for free with CreditWise b&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4bc3b8e-902d-488e-8a0d-d11968fdf1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7a8b3b92-29a7-408f-a632-adf497faab60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctaurl</name>
      <type>Main</type>
      <value>https://www.kbb.com/camp/creditwise?website=kbb&amp;channel=nend-onsite-ad&amp;placement=kbb-shopping-guide/</value>
      <webElementGuid>6086d463-c390-45b2-ae50-1e04c32823e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lean-auto</name>
      <type>Main</type>
      <value>hp-shop-guide-4</value>
      <webElementGuid>ef20c867-7702-4b7a-b735-354052638c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>InsurancePartner_CheckInsRates</value>
      <webElementGuid>b0af8cde-79ce-43b4-91a3-69cc778517bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-type</name>
      <type>Main</type>
      <value>click,impression</value>
      <webElementGuid>470629b9-8fee-432e-bd6b-2494357cbe40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-13rh4em etn5x2f11</value>
      <webElementGuid>420fb519-420d-41da-ba7d-390ca556f762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Know Your ScoreCar shopping? Check your credit health for free with CreditWise by Capital One.Check My Score</value>
      <webElementGuid>a62bf780-76a7-48b6-8cca-e63f98a933cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepModuleContainer&quot;)/div[@class=&quot;css-td2030 e6p01070&quot;]/div[@class=&quot;css-13rh4em etn5x2f11&quot;]</value>
      <webElementGuid>e1a89702-43f3-4be1-9c3f-b778a5e0b226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stepModuleContainer']/div/div[4]</value>
      <webElementGuid>a2ab6872-8527-4766-8c29-e6006a64f1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get My Offer'])[1]/following::div[1]</value>
      <webElementGuid>c4eb781f-2585-4a78-9d98-5b7f88a809e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get an Instant Cash Offer'])[1]/following::div[2]</value>
      <webElementGuid>b74d1376-5231-44b3-b26c-b62d9c3aa515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]</value>
      <webElementGuid>1347d465-5c9b-458c-aef1-61d0b2d8f8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Know Your ScoreCar shopping? Check your credit health for free with CreditWise by Capital One.Check My Score' or . = 'Know Your ScoreCar shopping? Check your credit health for free with CreditWise by Capital One.Check My Score')]</value>
      <webElementGuid>f7cd40bd-7e77-4b61-86ea-0a37971ed44f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
