<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Featured Content2024 Ford F150 Super Ca_80d5f7</name>
   <tag></tag>
   <elementGuidId>01bb8318-ed03-4b76-ae5a-e33117644fef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentFor_kbbAdsSimplifiedNativeAd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contentFor_kbbAdsSimplifiedNativeAd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#contentFor_kbbAdsSimplifiedNativeAd</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d55ed110-2813-48e8-81eb-d35cb543b914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFor_kbbAdsSimplifiedNativeAd</value>
      <webElementGuid>99af3dc8-3193-4ac2-b248-f6004214817a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Featured Content2024 Ford F150 Super Cab$43,175 Starting PriceThe 2024 Ford F-150 is simply a king among full-size pickup trucks, with talents and features that should please almost any potential buyer.Learn More  about 2024 Ford F150 Super Cab   about  </value>
      <webElementGuid>98eef071-4f50-427b-9c85-48208c162d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentFor_kbbAdsSimplifiedNativeAd&quot;)</value>
      <webElementGuid>b5dc541f-84b3-4782-bb96-b3d3e4400aa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='contentFor_kbbAdsSimplifiedNativeAd']</value>
      <webElementGuid>66344795-cd6a-4a18-a077-191a1d4ecbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div[5]/div/div/div[2]</value>
      <webElementGuid>69fbd167-408c-4b7c-8a69-e6cdefed4863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volvo'])[1]/following::div[9]</value>
      <webElementGuid>482680db-aa92-43fd-a31e-e4ff6e1ca9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VinFast'])[1]/following::div[13]</value>
      <webElementGuid>823226ea-921f-409d-8fb0-356f9b9bbc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[5]/div/div/div[2]</value>
      <webElementGuid>443004bf-ff35-41dd-b8a7-8f8082b27f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'contentFor_kbbAdsSimplifiedNativeAd' and (text() = 'Featured Content2024 Ford F150 Super Cab$43,175 Starting PriceThe 2024 Ford F-150 is simply a king among full-size pickup trucks, with talents and features that should please almost any potential buyer.Learn More  about 2024 Ford F150 Super Cab   about  ' or . = 'Featured Content2024 Ford F150 Super Cab$43,175 Starting PriceThe 2024 Ford F-150 is simply a king among full-size pickup trucks, with talents and features that should please almost any potential buyer.Learn More  about 2024 Ford F150 Super Cab   about  ')]</value>
      <webElementGuid>87e8232f-848d-431a-af5e-bb0d7f6e6371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
