<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Featured Content2024 Ford F150 Super Ca_86f03b</name>
   <tag></tag>
   <elementGuidId>a4f44d17-237a-4568-bf91-7d70b6956b90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentFor_kbbAdsSimplifiedNativeAd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contentFor_kbbAdsSimplifiedNativeAd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#contentFor_kbbAdsSimplifiedNativeAd</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba97416c-b22c-412d-bfc3-f01f2087e54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFor_kbbAdsSimplifiedNativeAd</value>
      <webElementGuid>e3518b7c-7ff1-445b-b78d-77b33946dca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Featured Content2024 Ford F150 Super Cab$43,175 Starting PriceThe 2024 Ford F-150 is simply a king among full-size pickup trucks, with talents and features that should please almost any potential buyer.Learn More</value>
      <webElementGuid>58da59fb-3d50-40ba-95f3-bf3d264b784e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentFor_kbbAdsSimplifiedNativeAd&quot;)</value>
      <webElementGuid>61f727ab-9a48-4946-98c0-c7cc90b709a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='contentFor_kbbAdsSimplifiedNativeAd']</value>
      <webElementGuid>71035004-0e31-4462-9123-f892de99c9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div[5]/div/div/div[2]</value>
      <webElementGuid>e4fdb77f-df01-4064-a483-7da5130b5560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volvo'])[1]/following::div[9]</value>
      <webElementGuid>aae47214-125a-4d37-9152-5d3bfa110a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VinFast'])[1]/following::div[13]</value>
      <webElementGuid>82a3282e-6522-48f7-a387-976d492f8643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[5]/div/div/div[2]</value>
      <webElementGuid>be627b67-4982-4a10-8019-d465b9accb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'contentFor_kbbAdsSimplifiedNativeAd' and (text() = 'Featured Content2024 Ford F150 Super Cab$43,175 Starting PriceThe 2024 Ford F-150 is simply a king among full-size pickup trucks, with talents and features that should please almost any potential buyer.Learn More' or . = 'Featured Content2024 Ford F150 Super Cab$43,175 Starting PriceThe 2024 Ford F-150 is simply a king among full-size pickup trucks, with talents and features that should please almost any potential buyer.Learn More')]</value>
      <webElementGuid>ff85a5ea-10e9-498b-a8e4-4f884df64694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
