<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Start with Your Current Car Get an esti_fc61f8</name>
   <tag></tag>
   <elementGuidId>7a871b88-06a2-44d6-9e6d-34c301a18436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stepModuleContainer']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-13rh4em.etn5x2f11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Start with Your Current Car Get an estimated value or a fixed offer to buy your &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a3eaa8d-9580-4e59-ab86-a66b86897fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>161a5b6b-b4dd-406c-833c-f1e2c64227bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctaurl</name>
      <type>Main</type>
      <value>https://www.kbb.com/whats-my-car-worth/</value>
      <webElementGuid>229e1f8d-2cb9-4840-bf3e-9f09259fefec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lean-auto</name>
      <type>Main</type>
      <value>hp-shop-guide-1</value>
      <webElementGuid>aa86c2f0-d451-4cbd-85a0-79268e0a4484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>Owners_GetMyCarValue</value>
      <webElementGuid>8c56d4d9-0008-43cc-b32b-fc5ebd0ffef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-type</name>
      <type>Main</type>
      <value>click,impression</value>
      <webElementGuid>814e89a4-be2f-4115-880c-7230117ec491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-13rh4em etn5x2f11</value>
      <webElementGuid>f2753b82-ec68-42e5-96d5-f63a313d2b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start with Your Current Car Get an estimated value or a fixed offer to buy your car.Get My Car's Value</value>
      <webElementGuid>1a4b866c-d184-436f-a59c-eb1f284d6509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepModuleContainer&quot;)/div[@class=&quot;css-td2030 e6p01070&quot;]/div[@class=&quot;css-13rh4em etn5x2f11&quot;]</value>
      <webElementGuid>6b34a617-4490-410d-b9e0-771ff8981c91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stepModuleContainer']/div/div</value>
      <webElementGuid>bba62b7a-2401-4401-bf24-c7b954b2144c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let Kelley Help You Shop Like a Pro'])[1]/following::div[4]</value>
      <webElementGuid>22f212ec-2074-4058-9fbc-1b29836f1908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Smart'])[1]/following::div[4]</value>
      <webElementGuid>598cb700-b6a4-4958-adff-d88248691335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>cac83635-c22a-4f8a-89a5-c6121678fdd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Start with Your Current Car Get an estimated value or a fixed offer to buy your car.Get My Car&quot; , &quot;'&quot; , &quot;s Value&quot;) or . = concat(&quot;Start with Your Current Car Get an estimated value or a fixed offer to buy your car.Get My Car&quot; , &quot;'&quot; , &quot;s Value&quot;))]</value>
      <webElementGuid>3ec4f146-4b31-4a7e-8e41-b129b84e7fca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
