<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Get an Instant Cash OfferUse it to purc_7f8737</name>
   <tag></tag>
   <elementGuidId>9b94cf76-be63-4030-aaf1-533a0fc702de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='stepModuleContainer']/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-13rh4em.etn5x2f11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Get an Instant Cash OfferUse it to purchase another car or walk away with a chec&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4966b06-f8b5-4158-b6ed-7e4aabe8312b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>adaf0b26-3511-479e-adfc-5b132c0722ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctaurl</name>
      <type>Main</type>
      <value>https://www.kbb.com/instant-cash-offer/?Lp=73111D1C-71E5-4563-8EED-03932B322D6C&amp;OfferCode=B&amp;LNX=KBBSHOPCARD&amp;isCombined=true</value>
      <webElementGuid>accdf2c3-2059-404f-85e7-420ebba3bcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lean-auto</name>
      <type>Main</type>
      <value>hp-shop-guide-3</value>
      <webElementGuid>49a5ece5-218a-4cea-8315-06b82ae73a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics</name>
      <type>Main</type>
      <value>ICO</value>
      <webElementGuid>aee0e5b7-bde0-4245-b3db-c0be5060a3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-type</name>
      <type>Main</type>
      <value>click,impression</value>
      <webElementGuid>95f01720-2099-4137-b3c5-aa6f0199adf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-13rh4em etn5x2f11</value>
      <webElementGuid>c472a924-9a3d-4bf9-98e4-82a138d1235d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get an Instant Cash OfferUse it to purchase another car or walk away with a check in hand.Get My Offer</value>
      <webElementGuid>6ed031dd-f9ad-4ee4-b3de-0a4bef9b4d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stepModuleContainer&quot;)/div[@class=&quot;css-td2030 e6p01070&quot;]/div[@class=&quot;css-13rh4em etn5x2f11&quot;]</value>
      <webElementGuid>21d13ca5-0105-4f66-be29-36c705ba8699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stepModuleContainer']/div/div[3]</value>
      <webElementGuid>11d4abb0-af9f-4a97-ab52-c81621d4935f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop this Car'])[1]/following::div[1]</value>
      <webElementGuid>3351a169-3a89-47df-9448-cf7b732e6156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starting Price'])[1]/following::div[3]</value>
      <webElementGuid>a733e58a-a510-4182-a364-7da95ae51853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[3]</value>
      <webElementGuid>b9cc24bd-70f6-4680-835e-3283f55f299b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Get an Instant Cash OfferUse it to purchase another car or walk away with a check in hand.Get My Offer' or . = 'Get an Instant Cash OfferUse it to purchase another car or walk away with a check in hand.Get My Offer')]</value>
      <webElementGuid>c68652c7-7068-4639-8a2b-22872dd56cff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
