<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Car ValuesPrice NewUsedMy Cars Value_6e214a</name>
   <tag></tag>
   <elementGuidId>29a8dc99-7fdf-4b30-897c-0309c714bc67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header.css-kzuwlq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>03f95e77-755f-43b2-a018-4e5e7e597087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-kzuwlq</value>
      <webElementGuid>71db63a0-e833-4d8c-bf96-fd3df5ede9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Car ValuesPrice New/UsedMy Car's ValueInstant Cash OfferCars for SaleCars for SaleFree Dealer Price QuoteVehicle History ReportFind Local DealersPrivate Seller ExchangePrivate Seller CarsSell Your CarCar ReviewsBest CarsDealer ReviewsKBB Expert ReviewsElectric Vehicle GuideKBB AwardsLatest Car NewsCar RepairAuto Repair PricesCar RecallsMaintenance PricingFind an Auto ShopService AdvisorOBD-II CodesResearch ToolsCar ResearchCar FinderCompare CarsVehicle History ReportCar ValuesCar LoansInsuranceCheck My CreditExtended WarrantyRecalls</value>
      <webElementGuid>2adaef61-4fb3-46c3-a243-aab383ded864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[@class=&quot;css-kzuwlq&quot;]</value>
      <webElementGuid>4cf6fde9-929f-461f-bbb0-f2db5d8a2917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header</value>
      <webElementGuid>23043080-efd5-4caa-9006-abbbd41aba73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>c4a6ecf0-d2f4-4258-ba7b-20ebd7276aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = concat(&quot;Car ValuesPrice New/UsedMy Car&quot; , &quot;'&quot; , &quot;s ValueInstant Cash OfferCars for SaleCars for SaleFree Dealer Price QuoteVehicle History ReportFind Local DealersPrivate Seller ExchangePrivate Seller CarsSell Your CarCar ReviewsBest CarsDealer ReviewsKBB Expert ReviewsElectric Vehicle GuideKBB AwardsLatest Car NewsCar RepairAuto Repair PricesCar RecallsMaintenance PricingFind an Auto ShopService AdvisorOBD-II CodesResearch ToolsCar ResearchCar FinderCompare CarsVehicle History ReportCar ValuesCar LoansInsuranceCheck My CreditExtended WarrantyRecalls&quot;) or . = concat(&quot;Car ValuesPrice New/UsedMy Car&quot; , &quot;'&quot; , &quot;s ValueInstant Cash OfferCars for SaleCars for SaleFree Dealer Price QuoteVehicle History ReportFind Local DealersPrivate Seller ExchangePrivate Seller CarsSell Your CarCar ReviewsBest CarsDealer ReviewsKBB Expert ReviewsElectric Vehicle GuideKBB AwardsLatest Car NewsCar RepairAuto Repair PricesCar RecallsMaintenance PricingFind an Auto ShopService AdvisorOBD-II CodesResearch ToolsCar ResearchCar FinderCompare CarsVehicle History ReportCar ValuesCar LoansInsuranceCheck My CreditExtended WarrantyRecalls&quot;))]</value>
      <webElementGuid>e37da0e1-f053-4f34-a3ac-2c7c30129b91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
